# Generated by Django 5.0.1 on 2024-02-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendrequest",
            name="sender_dhratchet_public_key",
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="friendrequest",
            name="sender_ik_public_key",
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="friendrequest",
            name="sender_opk_public_key",
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="friendrequest",
            name="sender_spk_public_key",
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Pending"), (2, "Accepted")], default=0
            ),
        ),
    ]
