# Generated by Django 5.0.1 on 2024-02-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_friendrequest_sender_dhratchet_public_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friendrequest",
            name="sender_dhratchet_public_key",
        ),
        migrations.RemoveField(
            model_name="friendrequest",
            name="sender_ik_public_key",
        ),
        migrations.RemoveField(
            model_name="friendrequest",
            name="sender_opk_public_key",
        ),
        migrations.RemoveField(
            model_name="friendrequest",
            name="sender_spk_public_key",
        ),
        migrations.AddField(
            model_name="friendrequest",
            name="key_bundle",
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
    ]
