# Generated by Django 5.0.1 on 2024-02-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_remove_friendrequest_sender_dhratchet_public_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendrequest",
            name="receiver_key_bundle",
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="receiver_key_bundle",
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="sender_key_bundle",
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
    ]
