# Generated by Django 5.0.1 on 2024-03-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_room_receiver_ratchet_room_sender_ratchet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendrequest",
            name="key_bundle",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="receiver_key_bundle",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="receiver_key_bundle",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="sender_key_bundle",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
