# Generated by Django 5.0.1 on 2024-03-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_alter_friendrequest_key_bundle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="public_key",
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
    ]
