# Generated by Django 5.0.1 on 2024-03-09 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_deviceidentifier_devices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="receiver_key_bundle",
        ),
        migrations.RemoveField(
            model_name="room",
            name="sender_key_bundle",
        ),
        migrations.AddField(
            model_name="friendrequest",
            name="receiver_device_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver_device_id",
                to="chat.deviceidentifier",
            ),
        ),
        migrations.AddField(
            model_name="friendrequest",
            name="sender_device_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender_device_id",
                to="chat.deviceidentifier",
            ),
        ),
        migrations.CreateModel(
            name="PublicKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_type",
                    models.IntegerField(choices=[(0, "Sender"), (1, "Receiver")]),
                ),
                ("key_bundle", models.BinaryField()),
                (
                    "device_identifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_key",
                        to="chat.deviceidentifier",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_key",
                        to="chat.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
