# Generated by Django 5.0.1 on 2024-03-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_alter_friendrequest_receiver_device_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendrequest",
            name="key_bundle",
            field=models.BinaryField(default=None),
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="receiver_key_bundle",
            field=models.BinaryField(default=None),
        ),
    ]
