# Generated by Django 5.0.1 on 2024-03-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_alter_friendrequest_key_bundle_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="receiver_ratchet",
        ),
        migrations.RemoveField(
            model_name="room",
            name="sender_ratchet",
        ),
        migrations.AddField(
            model_name="publickey",
            name="dhRatchet_key",
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
    ]
