# Generated by Django 5.0.1 on 2024-03-12 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0013_remove_room_receiver_ratchet_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publickey",
            name="device_identifier",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="public_key",
                to="chat.deviceidentifier",
            ),
        ),
    ]
