# Generated by Django 5.0.1 on 2024-03-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_alter_publickey_device_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devices",
            name="device_identifiers",
            field=models.ManyToManyField(
                related_name="device", to="chat.deviceidentifier"
            ),
        ),
    ]
