# Generated by Django 5.0.1 on 2024-03-13 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0015_alter_devices_device_identifiers"),
    ]

    operations = [
        migrations.CreateModel(
            name="RatchetPublicKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dhRatchet_key",
                    models.BinaryField(blank=True, default=None, null=True),
                ),
                (
                    "device_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_id",
                        to="chat.deviceidentifier",
                    ),
                ),
                (
                    "public_keys",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_keys",
                        to="chat.publickey",
                    ),
                ),
            ],
        ),
    ]
