# Generated by Django 5.0.1 on 2024-03-13 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0016_ratchetpublickey"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publickey",
            name="dhRatchet_key",
        ),
    ]
