# Generated by Django 5.0.1 on 2024-03-15 18:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0017_remove_publickey_dhratchet_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_device",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="receiver_device_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver_device_id",
                to="chat.userdevice",
            ),
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="sender_device_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender_device_id",
                to="chat.userdevice",
            ),
        ),
        migrations.AlterField(
            model_name="publickey",
            name="device_identifier",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="public_key",
                to="chat.userdevice",
            ),
        ),
        migrations.AlterField(
            model_name="ratchetpublickey",
            name="device_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_id",
                to="chat.userdevice",
            ),
        ),
        migrations.DeleteModel(
            name="Devices",
        ),
        migrations.DeleteModel(
            name="DeviceIdentifier",
        ),
    ]
