# Generated by Django 5.0.1 on 2024-03-15 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0018_device_userdevice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cipher", models.TextField(blank=True, max_length=10000, null=True)),
                ("public_key", models.BinaryField(blank=True, default=None, null=True)),
                (
                    "base_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_message",
                        to="chat.message",
                    ),
                ),
                (
                    "device_id",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_device_id",
                        to="chat.userdevice",
                    ),
                ),
            ],
        ),
    ]
