# Generated by Django 5.0.1 on 2024-03-15 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0019_childmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="childmessage",
            name="device_id",
        ),
        migrations.AddField(
            model_name="childmessage",
            name="receiver_device_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_receiver_device_id",
                to="chat.userdevice",
            ),
        ),
        migrations.AddField(
            model_name="childmessage",
            name="sender_device_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_sender_device_id",
                to="chat.userdevice",
            ),
        ),
    ]
