# Generated by Django 5.0.1 on 2024-03-16 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0020_remove_childmessage_device_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratchetpublickey",
            name="device_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_id",
                to="chat.userdevice",
            ),
        ),
    ]
