# Generated by Django 5.0.1 on 2024-03-16 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0021_alter_ratchetpublickey_device_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Device",
        ),
    ]
