# Generated by Django 5.0.1 on 2024-03-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0024_sentmessage_aes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="temp",
        ),
    ]
