# Generated by Django 5.0.1 on 2024-03-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0026_remove_message_public_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="childmessage",
            name="bytes_cipher",
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sentmessage",
            name="bytes_cipher",
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
    ]
