# Generated by Django 5.0.1 on 2024-03-20 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0027_childmessage_bytes_cipher_sentmessage_bytes_cipher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publickey",
            name="device_identifier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="public_key",
                to="chat.userdevice",
            ),
        ),
    ]
