# Generated by Django 5.0.1 on 2024-03-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0031_childmessage_private_key_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="childmessage",
            name="private_key_version",
        ),
        migrations.RemoveField(
            model_name="childmessage",
            name="public_key_version",
        ),
        migrations.AddField(
            model_name="childmessage",
            name="key_version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
