# Generated by Django 5.0.1 on 2024-03-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0034_userdevice_ip_address_userdevice_login_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="receiver_channel",
        ),
        migrations.RemoveField(
            model_name="room",
            name="sender_channel",
        ),
        migrations.AddField(
            model_name="room",
            name="receiver_message_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="sender_message_status",
            field=models.SmallIntegerField(default=-1),
        ),
    ]
