# Generated by Django 5.0.1 on 2024-03-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0035_remove_room_receiver_channel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publickey",
            name="ratchet_key",
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
    ]
