# Generated by Django 5.0.1 on 2024-03-23 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0036_publickey_ratchet_key"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RatchetPublicKey",
        ),
    ]
