# Generated by Django 5.0.1 on 2024-03-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0037_delete_ratchetpublickey"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="receiver_username",
        ),
        migrations.RemoveField(
            model_name="room",
            name="sender_username",
        ),
        migrations.AddField(
            model_name="room",
            name="receiver",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="sender",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
