# Generated by Django 5.0.1 on 2024-03-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0040_alter_room_receiver_message_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childmessage",
            name="cipher",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
