# Generated by Django 5.0.1 on 2024-03-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0041_alter_childmessage_cipher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentmessage",
            name="AES",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sentmessage",
            name="cipher",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
