# Generated by Django 5.0.1 on 2024-03-26 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0044_usersecure_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="publickey",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
