# Generated by Django 4.2.2 on 2023-06-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_userprofile_api"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="connected",
        ),
        migrations.AddField(
            model_name="client",
            name="client_id",
            field=models.CharField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="connected_clients",
            field=models.ManyToManyField(blank=True, to="main.client"),
        ),
        migrations.AlterField(
            model_name="client",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
