# Generated by Django 4.2.2 on 2024-01-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_room_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
