# Generated by Django 4.2.2 on 2024-01-23 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0006_alter_room_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="room",
            name="sender",
        ),
        migrations.AddField(
            model_name="message",
            name="receiver",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
