# Generated by Django 4.2.2 on 2024-01-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_remove_room_receiver_remove_room_sender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
