# Generated by Django 5.0.1 on 2024-02-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_userprofile_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="id",
        ),
        migrations.AddField(
            model_name="message",
            name="message_id",
            field=models.CharField(
                default="null", max_length=16, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
    ]
