# Generated by Django 5.0.1 on 2024-02-07 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_message_reply_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="reply_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="replies",
                to="main.message",
            ),
        ),
    ]
