# Generated by Django 5.0.1 on 2024-02-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_message_temp"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="receiver_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="room",
            name="sender_status",
            field=models.BooleanField(default=False),
        ),
    ]
