# Generated by Django 5.0.1 on 2024-02-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_room_receiver_username_room_sender_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="receiver_username",
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name="room",
            name="sender_username",
            field=models.CharField(default=None, max_length=128),
        ),
    ]
