# Generated by Django 5.0.1 on 2024-02-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_room_receiver_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="profile_pics/"),
        ),
    ]
