# Generated by Django 5.0.1 on 2024-02-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_alter_userprofile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(default=None, upload_to="profile_pics/"),
        ),
    ]
