# Generated by Django 5.0.1 on 2024-02-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_alter_userprofile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="auto_save",
            field=models.BooleanField(default=False),
        ),
    ]
