# Generated by Django 5.0.1 on 2024-02-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_userprofile_auto_save"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="saved",
            field=models.BooleanField(default=False),
        ),
    ]
