# Generated by Django 5.0.1 on 2024-02-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_message_image_url_alter_message_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="receiver_status",
        ),
        migrations.RemoveField(
            model_name="room",
            name="sender_status",
        ),
        migrations.AddField(
            model_name="room",
            name="receiver_channel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="sender_channel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
